.TH projman 1 "2004-10-14" "logilab projman"

.SH NAME 
.B projman_convert_format
 \- converts projman files

.SH SYNOPSIS 
.B projman 
[
.I command
] [
.I options
] [
.I FILES ...
]

.SH DESCRIPTION
Projman is a tool for project management and diagrams creation
projman_convert_format can be use to convert projects files between
formats. This tool is probably obsolete.

.SH COMMANDS

  projman <old_format_file.xml> <new_format_file.xml>
  projman_convert_format -d <old_format_files_in_directoconvert from old format to new

.SH SEE ALSO 
http://www.logilab.org/projects/projman/

.SH COPYRIGHT 
(c) 2004 Logilab. General Public Licence.

This program is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published 
by the Free Software Foundation; either version 2 of the License, 
or (at your option) any later version.

This program is distributed in the hope that it will be useful, 
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
GNU General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this program; if not, write to the Free Software 
Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
MA 02111-1307 USA.

.SH BUGS 
Full listing at http://intranet.logilab.fr/jpl/view?rql=728

.SH AUTHOR 
Logilab <contact@logilab.fr>
